# Generated by Django 3.0.5 on 2020-05-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='config',
            managers=[
            ],
        ),
    ]
