# Generated by Django 3.0.5 on 2020-09-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='today',
            field=models.IntegerField(default=1),
        ),
    ]
