# Generated by Django 3.0.5 on 2020-04-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audiofield',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
