# Generated by Django 3.0.5 on 2020-04-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscore',
            options={'ordering': ['-score', 'last_modified']},
        ),
        migrations.AddField(
            model_name='userscore',
            name='name',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='userscore',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
