# Generated by Django 3.0.5 on 2020-09-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userscore_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
