# Generated by Django 3.0.5 on 2020-09-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
