# Generated by Django 3.0.5 on 2020-09-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='imgurl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
