# Generated by Django 3.0.5 on 2020-09-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_userscore_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='imgurl',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
