# Generated by Django 3.0.5 on 2020-09-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200925_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
