# Generated by Django 3.0.5 on 2020-10-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200927_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-current_day', 'quiz_endtime']},
        ),
        migrations.AddField(
            model_name='config',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.CharField(default='N/A', max_length=555),
        ),
    ]
