# Generated by Django 3.0.5 on 2020-10-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200927_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['-current_day', 'quiz_endtime']},
        ),
    ]
