# Generated by Django 3.0.5 on 2020-10-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20201002_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.CharField(default='N/A', max_length=555),
        ),
    ]
