# Generated by Django 3.0.5 on 2020-10-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20201006_1556'),
        ('quiz', '0010_auto_20201003_1424'),
    ]

    operations = [
    ]
